- name: Set firewall rules and activate firewall
  hosts: all
  vars_files: 'variables.yml'
  remote_user: "{{ chost_user }}"
  become: true

  tasks:
    - name: Change default configuration to exclude IPv6-rules
      become: true
      ansible.builtin.lineinfile:
        path: /etc/default/ufw
        regexp: '^IPV6=yes'
        line: 'IPV6=no'

    - name: Disable and reset firewall (for playbook to be idempotent)
      become: true
      community.general.ufw:
        state: reset

    - name: Allow outgoing traffic
      become: true
      community.general.ufw:
        rule: allow
        direction: out

    - name: Allow ssh in
      become: true
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp
        direction: in

    - name: Allow http in
      become: true
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp
        direction: in

    - name: Allow https in
      become: true
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp
        direction: in

    - name: Deny remaining incoming traffic
      become: true
      community.general.ufw:
        rule: deny
        direction: in

    - name: Enable and activate
      become: true
      community.general.ufw:
        state: enabled
