- name: Set timezone and locale of server
  hosts: all
  vars_files: 'variables.yml'
  remote_user: "{{ chost_user }}"
  become: true

  tasks:
    - name: Set timezone
      community.general.timezone:
        name: "{{ system_timezone }}"

    - name: Ensure a locale exists
      community.general.locale_gen:
        name: "{{ system_locale }}"
        state: present

    - name: Set as default locale
      ansible.builtin.command: localectl set-locale {{ system_locale }}
      changed_when: true
# last line is an ugly fix to get by ansible-lint, should be implemented as in
# https://serverfault.com/questions/959026/how-do-i-generate-and-set-the-locale-using-ansible
